"""baseline

Revision ID: 0001_baseline
Revises:
Create Date: 2026-05-05 18:43:34.324710

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("actor_username", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("target_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("target_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("detail_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("ip_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_agent", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_actor_user_id"), "audit_logs", ["actor_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_actor_username"), "audit_logs", ["actor_username"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_event_type"), "audit_logs", ["event_type"], unique=False)
    op.create_index(op.f("ix_audit_logs_success"), "audit_logs", ["success"], unique=False)
    op.create_index(op.f("ix_audit_logs_target_id"), "audit_logs", ["target_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_target_type"), "audit_logs", ["target_type"], unique=False)
    op.create_table(
        "inventory_locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("part_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("part_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("location_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("zero_stock", sa.Boolean(), nullable=False),
        sa.Column("replacement_location_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_locations_location_code"),
        "inventory_locations",
        ["location_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_locations_part_key"), "inventory_locations", ["part_key"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_locations_status"), "inventory_locations", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_locations_zero_stock"),
        "inventory_locations",
        ["zero_stock"],
        unique=False,
    )
    op.create_table(
        "inventory_movements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("movement_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("part_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("location_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("order_no", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("scan_id", sa.Integer(), nullable=True),
        sa.Column("quantity_delta", sa.Integer(), nullable=False),
        sa.Column("before_qty", sa.Integer(), nullable=False),
        sa.Column("after_qty", sa.Integer(), nullable=False),
        sa.Column("operator_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_movements_location_code"),
        "inventory_movements",
        ["location_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_movement_type"),
        "inventory_movements",
        ["movement_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_operator_id"),
        "inventory_movements",
        ["operator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_order_no"), "inventory_movements", ["order_no"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_movements_part_key"), "inventory_movements", ["part_key"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_movements_scan_id"), "inventory_movements", ["scan_id"], unique=False
    )
    op.create_table(
        "outbound_progress_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_no", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("event", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("required_total", sa.Integer(), nullable=False),
        sa.Column("scanned_total", sa.Integer(), nullable=False),
        sa.Column("remaining_total", sa.Integer(), nullable=False),
        sa.Column("line_total", sa.Integer(), nullable=False),
        sa.Column("complete_line_total", sa.Integer(), nullable=False),
        sa.Column("active_scan_count", sa.Integer(), nullable=False),
        sa.Column("active_scan_quantity", sa.Integer(), nullable=False),
        sa.Column("operator_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("batch_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("scan_id", sa.Integer(), nullable=True),
        sa.Column("detail_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_outbound_progress_snapshots_batch_id"),
        "outbound_progress_snapshots",
        ["batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbound_progress_snapshots_event"),
        "outbound_progress_snapshots",
        ["event"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbound_progress_snapshots_operator_id"),
        "outbound_progress_snapshots",
        ["operator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbound_progress_snapshots_order_no"),
        "outbound_progress_snapshots",
        ["order_no"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbound_progress_snapshots_scan_id"),
        "outbound_progress_snapshots",
        ["scan_id"],
        unique=False,
    )
    op.create_table(
        "outbound_scans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_no", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("part_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("location_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("matched_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("operator_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("batch_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("record_id", sa.Integer(), nullable=True),
        sa.Column("void_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("voided_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("voided_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_outbound_scans_batch_id"), "outbound_scans", ["batch_id"], unique=False
    )
    op.create_index(
        op.f("ix_outbound_scans_location_code"), "outbound_scans", ["location_code"], unique=False
    )
    op.create_index(
        op.f("ix_outbound_scans_operator_id"), "outbound_scans", ["operator_id"], unique=False
    )
    op.create_index(
        op.f("ix_outbound_scans_order_no"), "outbound_scans", ["order_no"], unique=False
    )
    op.create_index(
        op.f("ix_outbound_scans_part_code"), "outbound_scans", ["part_code"], unique=False
    )
    op.create_index(
        op.f("ix_outbound_scans_record_id"), "outbound_scans", ["record_id"], unique=False
    )
    op.create_index(op.f("ix_outbound_scans_status"), "outbound_scans", ["status"], unique=False)
    op.create_index(
        op.f("ix_outbound_scans_voided_by"), "outbound_scans", ["voided_by"], unique=False
    )
    op.create_table(
        "records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("image_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sa.Enum("A", "B", "C", name="category"), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("vin_or_bin", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("serial_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("operator_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("raw_ocr_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("barcodes_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "uploaded",
                "ocr_done",
                "needs_review",
                "confirmed",
                "submitted",
                "submission_failed",
                "duplicate",
                name="recordstatus",
            ),
            nullable=False,
        ),
        sa.Column("submission_attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error_screenshot", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_records_model"), "records", ["model"], unique=False)
    op.create_index(op.f("ix_records_operator_id"), "records", ["operator_id"], unique=False)
    op.create_index(op.f("ix_records_serial_number"), "records", ["serial_number"], unique=False)
    op.create_index(op.f("ix_records_status"), "records", ["status"], unique=False)
    op.create_index(op.f("ix_records_vin_or_bin"), "records", ["vin_or_bin"], unique=False)
    op.create_table(
        "security_secrets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("secret_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_by_user_id", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_security_secrets_key"), "security_secrets", ["key"], unique=True)
    op.create_index(
        op.f("ix_security_secrets_updated_by_user_id"),
        "security_secrets",
        ["updated_by_user_id"],
        unique=False,
    )
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ip_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_agent", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_sessions_session_token_hash"),
        "user_sessions",
        ["session_token_hash"],
        unique=True,
    )
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("outbound_last_order_no", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_outbound_last_order_no"), "users", ["outbound_last_order_no"], unique=False
    )
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_index(
        "ux_inventory_locations_part_location",
        "inventory_locations",
        ["part_key", "location_code"],
        unique=True,
    )
    op.create_index(
        "ix_inventory_movements_part_created",
        "inventory_movements",
        ["part_key", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_movements_order",
        "inventory_movements",
        ["order_no"],
        unique=False,
    )
    op.create_index("ux_users_username", "users", ["username"], unique=True)
    op.create_index("ux_user_sessions_token", "user_sessions", ["session_token_hash"], unique=True)
    op.create_index("ux_security_secrets_key", "security_secrets", ["key"], unique=True)
    op.execute(
        sa.text(
            "CREATE UNIQUE INDEX ux_records_vin_or_bin "
            "ON records(vin_or_bin) "
            "WHERE vin_or_bin IS NOT NULL AND status != 'duplicate'"
        )
    )
    op.execute(
        sa.text(
            "CREATE UNIQUE INDEX ux_records_serial_number "
            "ON records(serial_number) "
            "WHERE serial_number IS NOT NULL AND status != 'duplicate'"
        )
    )
    op.execute(
        sa.text(
            "CREATE UNIQUE INDEX ux_outbound_scans_record "
            "ON outbound_scans(order_no, part_code, record_id) "
            "WHERE record_id IS NOT NULL AND status = 'active'"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ux_outbound_scans_record", table_name="outbound_scans")
    op.drop_index("ux_records_serial_number", table_name="records")
    op.drop_index("ux_records_vin_or_bin", table_name="records")
    op.drop_index("ux_security_secrets_key", table_name="security_secrets")
    op.drop_index("ux_user_sessions_token", table_name="user_sessions")
    op.drop_index("ux_users_username", table_name="users")
    op.drop_index("ix_inventory_movements_order", table_name="inventory_movements")
    op.drop_index("ix_inventory_movements_part_created", table_name="inventory_movements")
    op.drop_index("ux_inventory_locations_part_location", table_name="inventory_locations")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_status"), table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_outbound_last_order_no"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_session_token_hash"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index(op.f("ix_security_secrets_updated_by_user_id"), table_name="security_secrets")
    op.drop_index(op.f("ix_security_secrets_key"), table_name="security_secrets")
    op.drop_table("security_secrets")
    op.drop_index(op.f("ix_records_vin_or_bin"), table_name="records")
    op.drop_index(op.f("ix_records_status"), table_name="records")
    op.drop_index(op.f("ix_records_serial_number"), table_name="records")
    op.drop_index(op.f("ix_records_operator_id"), table_name="records")
    op.drop_index(op.f("ix_records_model"), table_name="records")
    op.drop_table("records")
    op.drop_index(op.f("ix_outbound_scans_voided_by"), table_name="outbound_scans")
    op.drop_index(op.f("ix_outbound_scans_status"), table_name="outbound_scans")
    op.drop_index(op.f("ix_outbound_scans_record_id"), table_name="outbound_scans")
    op.drop_index(op.f("ix_outbound_scans_part_code"), table_name="outbound_scans")
    op.drop_index(op.f("ix_outbound_scans_order_no"), table_name="outbound_scans")
    op.drop_index(op.f("ix_outbound_scans_operator_id"), table_name="outbound_scans")
    op.drop_index(op.f("ix_outbound_scans_location_code"), table_name="outbound_scans")
    op.drop_index(op.f("ix_outbound_scans_batch_id"), table_name="outbound_scans")
    op.drop_table("outbound_scans")
    op.drop_index(
        op.f("ix_outbound_progress_snapshots_scan_id"), table_name="outbound_progress_snapshots"
    )
    op.drop_index(
        op.f("ix_outbound_progress_snapshots_order_no"), table_name="outbound_progress_snapshots"
    )
    op.drop_index(
        op.f("ix_outbound_progress_snapshots_operator_id"), table_name="outbound_progress_snapshots"
    )
    op.drop_index(
        op.f("ix_outbound_progress_snapshots_event"), table_name="outbound_progress_snapshots"
    )
    op.drop_index(
        op.f("ix_outbound_progress_snapshots_batch_id"), table_name="outbound_progress_snapshots"
    )
    op.drop_table("outbound_progress_snapshots")
    op.drop_index(op.f("ix_inventory_movements_scan_id"), table_name="inventory_movements")
    op.drop_index(op.f("ix_inventory_movements_part_key"), table_name="inventory_movements")
    op.drop_index(op.f("ix_inventory_movements_order_no"), table_name="inventory_movements")
    op.drop_index(op.f("ix_inventory_movements_operator_id"), table_name="inventory_movements")
    op.drop_index(op.f("ix_inventory_movements_movement_type"), table_name="inventory_movements")
    op.drop_index(op.f("ix_inventory_movements_location_code"), table_name="inventory_movements")
    op.drop_table("inventory_movements")
    op.drop_index(op.f("ix_inventory_locations_zero_stock"), table_name="inventory_locations")
    op.drop_index(op.f("ix_inventory_locations_status"), table_name="inventory_locations")
    op.drop_index(op.f("ix_inventory_locations_part_key"), table_name="inventory_locations")
    op.drop_index(op.f("ix_inventory_locations_location_code"), table_name="inventory_locations")
    op.drop_table("inventory_locations")
    op.drop_index(op.f("ix_audit_logs_target_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_target_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_success"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_event_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_username"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_user_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
